# Generated by Django 5.0.4 on 2024-05-18 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno_text_uz", models.TextField()),
                ("anno_text_eng", models.TextField(null=True)),
                ("anno_date", models.DateField()),
                ("anno_author", models.CharField(max_length=255)),
                ("anno_view", models.IntegerField()),
                ("anno_keyword", models.CharField(max_length=255)),
                ("anno_file", models.BinaryField()),
            ],
            options={
                "verbose_name": "Annotation",
                "verbose_name_plural": "annotations",
                "db_table": "annotations",
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paper_name_uz", models.CharField(max_length=255)),
                ("paper_name_eng", models.CharField(max_length=255, null=True)),
                ("paper_desc_uz", models.CharField(max_length=255)),
                ("paper_desc_eng", models.CharField(max_length=255, null=True)),
                ("paper_text_uz", models.TextField()),
                ("paper_text_eng", models.TextField(null=True)),
                ("paper_date", models.DateField()),
                ("paper_author", models.CharField(max_length=255)),
                ("paper_view", models.IntegerField()),
                ("paper_code", models.IntegerField()),
                ("paper_file", models.BinaryField()),
            ],
            options={
                "verbose_name": "Paper",
                "verbose_name_plural": "papers",
                "db_table": "papers",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_text_uz", models.TextField()),
                ("article_text_eng", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "articles",
                "db_table": "articles",
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_name_uz", models.CharField(max_length=255)),
                ("reference_name_eng", models.CharField(max_length=255, null=True)),
                ("reference_text_uz", models.TextField()),
                ("reference_text_eng", models.TextField(null=True)),
                (
                    "reference_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_publications.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference",
                "verbose_name_plural": "references",
                "db_table": "references",
            },
        ),
    ]
