# Generated by Django 5.0.4 on 2024-05-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_sender", models.EmailField(max_length=254)),
                ("contact_message", models.TextField()),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "contact",
                "db_table": "contacs",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faq_question_uz", models.CharField(max_length=255)),
                ("faq_question_eng", models.CharField(max_length=255, null=True)),
                ("faq_answer_uz", models.TextField()),
                ("faq_answer_eng", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "faq",
                "db_table": "faqs",
            },
        ),
        migrations.CreateModel(
            name="Requirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement_name_uz", models.CharField(max_length=255)),
                ("requirement_name_eng", models.CharField(max_length=255, null=True)),
                ("requirement_text_uz", models.TextField()),
                ("requirement_text_eng", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Requirement",
                "verbose_name_plural": "requirement",
                "db_table": "requirements",
            },
        ),
    ]
