# Generated by Django 5.0.4 on 2024-05-18 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Gender",
                "verbose_name_plural": "gender",
                "db_table": "genders",
            },
        ),
        migrations.CreateModel(
            name="PublicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=255)),
                ("type_desc", models.CharField(max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Pubtypes",
                "verbose_name_plural": "pubtype",
                "db_table": "pubtypes",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("author_lastname", models.CharField(max_length=255)),
                ("author_age", models.IntegerField()),
                ("author_country", models.CharField(max_length=255)),
                (
                    "author_gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_publications.gender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "author",
                "db_table": "authors",
            },
        ),
        migrations.CreateModel(
            name="Publications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_name_uz", models.CharField(max_length=255)),
                ("pub_name_eng", models.CharField(max_length=255, null=True)),
                ("pub_text_uz", models.TextField()),
                ("pub_text_eng", models.CharField(max_length=255, null=True)),
                ("pub_date", models.DateField()),
                ("pub_tegs", models.CharField(max_length=255)),
                ("pub_img", models.BinaryField()),
                ("pub_desc_uz", models.CharField(max_length=255)),
                ("pub_desc_eng", models.CharField(max_length=255, null=True)),
                ("pub_code", models.IntegerField()),
                ("pub_file", models.BinaryField()),
                (
                    "pub_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_publications.author",
                    ),
                ),
                (
                    "pub_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_publications.publicationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "publication",
                "db_table": "publication",
            },
        ),
    ]
